# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordergoods_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='score',
            field=models.SmallIntegerField(choices=[(0, '0分'), (1, '20分'), (2, '40分'), (3, '60分'), (4, '80分'), (5, '100分')], default=5, verbose_name='满意度评分'),
        ),
    ]
