# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180425_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='是否匿名评价'),
        ),
    ]
