# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-21 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_ordergoods_is_commented'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordergoods',
            options={'verbose_name': '订单商品', 'verbose_name_plural': '订单商品'},
        ),
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'verbose_name': '订单基本信息', 'verbose_name_plural': '订单基本信息'},
        ),
    ]
