# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180412_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='default_image',
        ),
        migrations.AddField(
            model_name='sku',
            name='default_image_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='默认图片'),
        ),
    ]
